### PR TITLE
Test against all Rails versions

### PR DESCRIPTION
**Pull request by joneslee85**
Let's try to keep Thomas & friends happy

### CODE REVIEW

**Comment by sj26** [comment]
Hmm. Rails 3.0 used a flash hash directly descended from a hash, which is very different to 3.1 and 3.2 which have internal hashes. The rails 2 implementation may actually be more appropriate. I'll investigate a little.

In any case, this shouldn't be a problem for us.

**Comment by johnsyweb** [comment]
This nicely illustrates https://github.com/envato/rails_4_session_flash_backport/issues/13 , thanks.

**Comment by sj26** [comment]
Might want to pull in 45a0b26302c4f16402c26664956a9936bf25d91e for a complete 3.0 gemfile.

**Comment by sj26** [comment]
So it turns out rails 3.0 used something between rails 2.x and 3.1's solution. Here's a partial implementation: https://github.com/envato/rails_4_session_flash_backport/compare/rails-3-0-support Unfortunately I don't think we can achieve full compatibility.

In rails 3.0 the FlashHash still descends from Hash. This means it's marshalled as a user_class descending from hash, not a plain object, so unmarshalling existing values to migrate will fail. If you've already had this gem installed since 2.3 it should be seamless. But if you start on 3.0 and go to 3.1 I think you must just lose your sessions/flashes anyway. How have we handled this in the past?

Here's a gist of the marshal streams for reference: https://gist.github.com/sj26/75b3a18c0c8854e562e1

**Comment by sj26** [comment]
I popped some more commits on the end to cover more matrix entries, and mark rails 3.0 as acceptable failures for now.

**Pull request merged**
