### PR TITLE
Rails 4 #to_session_value should include discard as array

### PR DESCRIPTION
**Pull request by NVerban**
#### Context

Upon removing this gem from our (rather large) Rails 4.1 application, errors started occurring due to FlashHash objects being initialised with discard value as nil, which [ActionDispatch ::FlashHash#stringify_array](https://github.com/rails/rails/blob/4-1-stable/actionpack/lib/action_dispatch/middleware/flash.rb#L98) doesn't like when it was trying to map over a value that doesn't exist causing the good old `undefined method 'map' for nil:NilClass` error.

When patching `#to_session_value`,  `value['discard']` should also be present, as per https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_dispatch/middleware/flash.rb#L91

#### Changes

- Updated return value of `#to_session_value` to include `discard` as array.

### CODE REVIEW

**Comment by shevaun** [comment]
Awesome work @jverban, thanks for figuring out how we can finally get rid of this gem!!

**Review by shevaun — APPROVED** [review]

**Comment by shevaun** [comment]
We should update the version number of the gem with this patch, so we can upgrade it on market when we're ready

**Comment by lparry** [comment]
I've been marked to be a reviewer, but seeing as I haven't used or looked at this gem in about 5 years, I'm gonna leave that to people with the current context

**Comment by shevaun** [comment]
👍 
 You could try get a review from @mariovisic too?

**Comment by shevaun** [comment]
I'm just wondering... even after market is using this version of the gem, how can we ensure all sessions have been updated with a correct `discards` value, so that we can then remove the gem?

**Comment by jverban** [comment]
Great question @shevaun I think probably the best method is to leave it a day or two - seeing as this is the user's session which only lasts until they close their browser, and the flash is discarded on next action/request.

**Comment by mariovisic** [comment]
Nice find, well done 👍

**Review by mariovisic — APPROVED** [review]

**Review by viraptor — APPROVED** [review]
The change looks good, but are you sure you want to bump up the version in the same PR?

**Pull request merged**
